#!/bin/bash
systemctl start nginx
rm /etc/nginx/sites-enabled/default
echo "server { listen 80; }" > /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
